### PR TITLE
Added permission

### PR DESCRIPTION
**Pull request by celia233**
Groups have to be created in the admin page to work(GateKeeper/Committee)

### CODE REVIEW

**Comment by celia233** [comment]
added some permissions

**Comment by TinBryn** [comment]
Did you test that this works? It looks like urls.py won't work.

**Comment by TinBryn** [comment]
It looks like urls.py is missing a comma, before the new additions, as you've forked the repository it's a little more work to test, can you make sure those urls are working.

**Comment by TinBryn** [comment]
I will have to at the moment recommend against merging this until it can be made functional.

**Pull request closed without merging**
