### PR TITLE
Rudimentary edit forms for both members and library

### PR DESCRIPTION
**Pull request by Felstar9975**
-Created views for the forms and edits/updates
-Created new urls
-Created templates for the new forms

-Missing edit buttons in the item/members description pages, but can use urls

### CODE REVIEW

**Comment by TinBryn** [comment]
I think this conflicts with my recent change, do you mind if I do a few edits on your branch to resolve the conflicts?

**Comment by TinBryn** [comment]
I merged master into Laurent's branch and made his additions consistent with my changes. Since this is now both Laurent's and my work, can Miguel review it?

**Comment by TinBryn** [comment]
@Felstar9975 Did you have a link to the edit forms?, because I can't find them now or in previous versions

**Comment by Felstar9975** [comment]
@TinBryn I added urls to both apps which should work similarly to the description page urls, I just haven't added the edit buttons in yet.

**Comment by TinBryn** [comment]
Ok then. I did test the urls, I was just afraid I clobbered something.

**Comment by TinBryn** [comment]
Waiting on @sirmiggles is just delaying everything. There is no reason to delay this merge any longer.

**Pull request merged**
