### PR TITLE
Template refactor and finally removed public secret key

### PR DESCRIPTION
**Pull request by TinBryn**
If we want to add anything to the just the library as a whole it should be easy to do now.

I finally made it so that there is no longer a public secret key

### CODE REVIEW

**Comment by TinBryn** [comment]
I haven't gotten it to persist in venv, but it runs. If the variables are set otherwise it should do the right thing.

**Review by sirmiggles — COMMENTED** [review]
`library/base.html` creates a redundant HTML sheet -- false layer of abstraction.
Original was more intuitive as it wrapped actual content - this, according to `Django` would be a blank HTML sheet.

**Comment by sirmiggles** [comment]
> `library/base.html` creates a redundant HTML sheet -- false layer of abstraction.
> Original was more intuitive as it wrapped actual content - this, according to `Django` would be a blank HTML sheet.

Scratch this thought - found a way to template with these changes. Was just annoying because of different number of columns.

**Comment by TinBryn** [comment]
This was not intended to change any behavior, it's a pure refactor, but it makes it easy to apply library wide changes, but just to the library

**Pull request merged**
